In [1]:
import pandas as pd
import numpy as np
file = pd.read_csv("Database.csv")
file

,Unnamed: 0,Gene Sequence,Cultivar ID,Plant Height(cm),Subpopulation
0,0,ACCGATCTT,W128,149.800000,Intermediate
1,1,GCCGTACTT,W030,172.600000,Indica Intermediate
2,2,GCCGTACTC,W049,156.900000,Aus
3,3,GCCGTACTC,W134,156.900000,Aus
4,4,GCCGTACCC,W256,145.100000,VI/Aromatic
...,...,...,...,...,...
523,523,GCTGTTTTC,C099,142.911667,Intermediate
524,524,GCTGTTTTC,W033,142.911667,Intermediate
525,525,GCTGTTTTC,W192,142.911667,Intermediate
526,526,GCTGTTTTC,C066,142.911667,Intermediate
527,527,GCTGTTTTC,W107,142.911667,Intermediate

In [2]:
legend = {'A': 1,'T': 2,'C':3,'G': 4}
encoded=[]
for i in file['Gene Sequence']:
  score = ""
  for j in i:
    score += str(legend[j])
  encoded.append(int(score))

In [3]:
del file['Unnamed: 0']

In [4]:
file['Gene Sequence'] = encoded

In [5]:
file

     Gene Sequence Cultivar ID  Plant Height(cm)        Subpopulation
0        133412322        W128        149.800000         Intermediate
1        433421322        W030        172.600000  Indica Intermediate
2        433421323        W049        156.900000                  Aus
3        433421323        W134        156.900000                  Aus
4        433421333        W256        145.100000          VI/Aromatic
..             ...         ...               ...                  ...
523      432422223        C099        142.911667         Intermediate
524      432422223        W033        142.911667         Intermediate
525      432422223        W192        142.911667         Intermediate
526      432422223        C066        142.911667         Intermediate
527      432422223        W107        142.911667         Intermediate

[528 rows x 4 columns]

In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# prepare data for training
X = file['Gene Sequence'].values
y_subpop = file['Subpopulation'].values

# split the data into training and test sets
X_train, X_test, y_train_subpop, y_test_subpop = train_test_split(X, y_subpop, test_size = 0.28, random_state = 42)
X_train = X_train.reshape(-1, 1)
X_test = X_test.reshape(-1, 1)

# fit the random forest classifier for predicting subpopulation
rfc_subpop = RandomForestClassifier(n_estimators = 100, random_state = 42, max_depth = 10)
rfc_subpop.fit(X_train, y_train_subpop)

# predict the test set for subpopulation
y_pred_subpop = rfc_subpop.predict(X_test)

# calculate accuracy score for subpopulation prediction
acc_score_subpop = accuracy_score(y_test_subpop, y_pred_subpop)
print("Accuracy score for subpopulation prediction: {:.0f}%".format(acc_score_subpop*100))

Accuracy score for subpopulation prediction: 89%

In [7]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# extract features and target variable
x = file['Gene Sequence'].values
y = file['Plant Height(cm)'].values

# split data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 42)
x_train = x_train.reshape(-1, 1)
x_test = x_test.reshape(-1, 1)
# fit the regressor
regressor = RandomForestRegressor(n_estimators = 100, random_state = 42, max_depth = 10)
regressor.fit(x_train, y_train)

# predict on the test set
y_pred = regressor.predict(x_test)

# evaluate the model
from sklearn.metrics import r2_score
print("R^2 score: {:.0f}".format(r2_score(y_test, y_pred)*100))

R^2 score: 85

In [8]:
primary = pd.read_csv("Primary.csv")
primary = np.array(primary)
primary = primary.reshape(-1)

In [14]:
input_sequence = input("DNA Sequence: ")
print("Input Sequence:",input_sequence)
input_list = list(input_sequence)
for i in range(len(input_sequence)):
    if input_sequence[i] == "N":
        input_list[i] = primary[i]
final_sequence = ''.join(input_list)
legend = {'A': 1, 'T': 2, 'C': 3, 'G': 4}
string = ""
for i in final_sequence:
    for j in i:
        string += str(legend[j])
score = np.array(int(string))
score = score.reshape(1, -1)
predicted_height = regressor.predict(score)
predicted_subpopulation = rfc_subpop.predict(score)
print("Plant Height: {:.2f} cm".format(predicted_height[0]))
print("Subpopulation: {}".format(predicted_subpopulation[0]))

Input Sequence: GCTAACCTA
Plant Height: 153.13 cm
Subpopulation: Tropical Japonica