In [7]:
import pandas as pd

In [8]:
file = pd.read_csv("Data.csv")
file

     Unnamed: 0  index cultivar id  sequences  height        subpopulation
0             0      0        W128  ACCGATCTT  149.80         Intermediate
1             1      1        W030  GCCGTACTT  172.60  Indica Intermediate
2             2      2        W049  GCCGTACTC  163.80                  Aus
3             3      2        W134  GCCGTACTC  150.00                  Aus
4             4      3        W256  GCCGTACCC  160.00          VI/Aromatic
..          ...    ...         ...        ...     ...                  ...
523         524     67        C099  GCTGTTTTC  176.80  Indica Intermediate
524         525     67        W033  GCTGTTTTC  155.00             Indica I
525         526     67        W192  GCTGTTTTC  121.20         Intermediate
526         527     67        C066  GCTGTTTTC  120.27             Indica I
527         528     67        W107  GCTGTTTTC  163.20  Indica Intermediate

[528 rows x 6 columns]

In [9]:
file.columns

Index(['Unnamed: 0', 'index', 'cultivar id', 'sequences', 'height',
       'subpopulation'],
      dtype='object')

In [10]:
del file['Unnamed: 0']

In [12]:
file = file.rename(columns = {"index" : "Clustar Number", "cultivar id": "Cultivar ID"
                              ,"sequences" : "Gene Sequence", "height" : "Plant Height(cm)"
                              ,"subpopulation" : "Subpopulation"})

In [13]:
file

,Clustar Number,Cultivar ID,Gene Sequence,Plant Height(cm),Subpopulation
0,0,W128,ACCGATCTT,149.80,Intermediate
1,1,W030,GCCGTACTT,172.60,Indica Intermediate
2,2,W049,GCCGTACTC,163.80,Aus
3,2,W134,GCCGTACTC,150.00,Aus
4,3,W256,GCCGTACCC,160.00,VI/Aromatic
...,...,...,...,...,...
523,67,C099,GCTGTTTTC,176.80,Indica Intermediate
524,67,W033,GCTGTTTTC,155.00,Indica I
525,67,W192,GCTGTTTTC,121.20,Intermediate
526,67,C066,GCTGTTTTC,120.27,Indica I
527,67,W107,GCTGTTTTC,163.20,Indica Intermediate

In [14]:
import numpy as np
height_range = []
for i in range(68):
    final_height = 0
    plant_height = []
    for j in range(len(file['Clustar Number'])):
        if (file['Clustar Number'][j] == i):
            plant_height.append(file['Plant Height(cm)'][j])
    final_height = np.mean(plant_height)
    for k in range(len(plant_height)):
        height_range.append(final_height)

In [15]:
from statistics import mode
common_sub = []
for i in range(68):
    sub_name = []
    for j in range(len(file['Clustar Number'])):
        if (file['Clustar Number'][j] == i):
            sub_name.append(file['Subpopulation'][j])
    if (len(sub_name) == 2):sub_name[1] = sub_name[0]
    else:
        sub_mode = mode(sub_name)
        for k in range(len(sub_name)):sub_name[k] = sub_mode
    for k in range(len(sub_name)):
        common_sub.append(sub_name)

In [19]:
database = pd.DataFrame(columns = ['Gene Sequence', 'Cultivar ID', 'Plant Height(cm)', 'Subpopulation'])
for i in range(len(file['Gene Sequence'])):
    database.loc[i, 'Gene Sequence'] = file.loc[i, 'Gene Sequence']
    database.loc[i, 'Cultivar ID'] = file.loc[i, 'Cultivar ID']
    database.loc[i, 'Plant Height(cm)'] = height_range[i]
    database.loc[i, 'Subpopulation'] = common_sub[i][0]
database.to_csv("Database.csv")